# --- !Ups

CREATE TABLE SIGNALEMENT
(
    ID UUID PRIMARY KEY,
    TYPE_ETABLISSEMENT VARCHAR NOT NULL,
    CATEGORIE_ANOMALIE VARCHAR NOT NULL,
    PRECISION_ANOMALIE VARCHAR NOT NULL,
    NOM_ETABLISSEMENT VARCHAR NOT NULL,
    ADRESSE_ETABLISSEMENT VARCHAR NOT NULL,
    DESCRIPTION VARCHAR,
    PRENOM VARCHAR NOT NULL,
    NOM VARCHAR NOT NULL,
    EMAIL VARCHAR NOT NULL,
    PHOTO OID
);

# --- !Downs

DROP TABLE SIGNALEMENT;