# --- !Ups

ALTER TABLE USERS RENAME COLUMN EMAIL TO LOGIN;
ALTER TABLE USERS ADD CONSTRAINT LOGIN_UNIQUE UNIQUE(LOGIN);

ALTER TABLE USERS ADD COLUMN EMAIL VARCHAR;
UPDATE USERS SET EMAIL = LOGIN;


ALTER TABLE USERS ADD COLUMN ACTIVATION_KEY VARCHAR;

ALTER TABLE USERS ALTER COLUMN FIRSTNAME DROP NOT NULL;
ALTER TABLE USERS ALTER COLUMN LASTNAME DROP NOT NULL;

CREATE TABLE AUTH_TOKENS
(
    ID UUID PRIMARY KEY,
    USER_ID UUID NOT NULL,
    EXPIRY TIMESTAMP NOT NULL
);

ALTER TABLE AUTH_TOKENS ADD CONSTRAINT USER_AUTH_TOKEN UNIQUE(USER_ID);

# --- !Downs

ALTER TABLE USERS DROP COLUMN EMAIL;

ALTER TABLE USERS DROP CONSTRAINT LOGIN_UNIQUE;
ALTER TABLE USERS RENAME COLUMN LOGIN TO EMAIL;

ALTER TABLE USERS DROP COLUMN ACTIVATION_KEY;

DROP TABLE AUTH_TOKENS;