# --- !Ups

CREATE TABLE RATINGS
(
    ID UUID PRIMARY KEY,
    CREATION_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
    CATEGORY VARCHAR NOT NULL,
    SUBCATEGORIES VARCHAR[],
    POSITIVE BOOLEAN NOT NULL
);

# --- !Downs

DROP TABLE RATINGS
