# --- !Ups

CREATE TABLE PIECE_JOINTE
(
    ID UUID PRIMARY KEY,
    SIGNALEMENT_ID UUID,
    DATE_CREATION TIMESTAMP NOT NULL,
    NOM VARCHAR NOT NULL
);

ALTER TABLE SIGNALEMENT ADD COLUMN PIECE_JOINTE_IDS UUID[];

# --- !Downs

DROP TABLE PIECE_JOINTE;

ALTER TABLE SIGNALEMENT DROP PIECE_JOINTE_IDS;