# --- !Ups

ALTER TABLE SIGNALEMENT ALTER COLUMN date_constat DROP NOT NULL;

ALTER TABLE SIGNALEMENT ALTER COLUMN precision TYPE VARCHAR[] USING array[precision];
ALTER TABLE SIGNALEMENT RENAME COLUMN precision TO details;

ALTER TABLE SIGNALEMENT ALTER COLUMN sous_categorie TYPE VARCHAR[] USING array[sous_categorie];
ALTER TABLE SIGNALEMENT RENAME COLUMN sous_categorie TO sous_categories;

# --- !Downs

ALTER TABLE SIGNALEMENT RENAME COLUMN details TO precision;
ALTER TABLE SIGNALEMENT ALTER COLUMN precision TYPE VARCHAR USING precision[1];

ALTER TABLE SIGNALEMENT RENAME COLUMN sous_categories TO sous_categorie;
ALTER TABLE SIGNALEMENT ALTER COLUMN sous_categorie TYPE VARCHAR USING sous_categorie[1];
