addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.16")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.6")
//addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.0.0")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.10.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.3.3")
//addSbtPlugin("com.github.cb372"                  % "sbt-explicit-dependencies" % "0.2.15")
